#  Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: validate_beegfs_vars.yml
beegfs_support_success_msg: "beegfs_support validated successfully"
beegfs_support_failure_msg: "Failed. beegfs_support should be either true or false"

# Usage: fetch_beegfs_inputs.yml
beegfs_rdma_support_success_msg: "beegfs_rdma_support validated successfully"
beegfs_rdma_support_failure_msg: "Failed. beegfs_rdma_support should be either true or false"
beegfs_mgmt_server_success_msg: "beegfs_mgmt_server, validated successfully"
beegfs_mgmt_server_fail_msg: "Failed. Please enter IP of management server in IPV4 format"
beegfs_mgmt_server_not_reachable_msg: "Failure, IP provided for beegfs_mgmt_server is not reachable. Please provide reachable IP of beegfs management server"
beegfs_mounts_fail_msg: "Failed. Please provide a path for mounting beegfs file system"
beegfs_client_version_success_msg: "beegfs_client_version, validated successfully "
beegfs_client_version_fail_msg: "Failed, Please provide beegfs_client_version grater than 7.2"
beegfs_non_leap_repo: "https://www.beegfs.io/release/beegfs_{{ beegfs_client_version }}/dists/beegfs-rhel8.repo"
beegfs_repo_status_msg: "Failed. Value entered for beegfs_client_version is not valid. Please enter valid beegfs client version by checking beegfs release page"
beegfs_unmount_client_success_msg: "beegfs_unmount_client validated successfully"
beegfs_unmount_client_failure_msg: "beegfs_unmount_client value should be either true or false"
beegfs_version_change_success_msg: "beegfs_version_change validated successfully"
beegfs_version_change_failure_msg: "beegfs_version_change value should be either true or false"
unmount_success_msg: "beegfs_unmount_client validated successfully"
unmount_failure_msg: "beegfs_unmount_client should be true only when beegfs_version change is true or there is a change in mount location"
latest_version: 7.3.0
compatability_msg: "Upgradation to 7.3.0 is not possible, as it is not supported by beegfs, try upgrading to some other versions"
beegfs_shared_secret_failure_msg: "[WARNING] Missing shared secret (connauth) file.
connauth file configured in server, meta and storage should be provided in beegfs_secret_storage_filepath variable in storage_config.yml
for beegfs client version >= 7.2.7"
warning_wait_time: 10

# Usage: fetch_nfs_client_params.yml
nfs_server_reach_msg: "Failed. Nfs server is not reachable. Please enter valid nfs server IP in nfs_client_params"
server_share_path_success_msg: "server_share_path is validated successfully"
server_share_path_fail_msg: "Failed, Declare server_share_path variable in nfs_client_params of storage_config, please refer comments in storage_config.yml"
server_share_path_failure_msg: "Failed. Please enter valid NFS server mount location"
server_ip_success_msg: "Successfully verified server_ip variable declaration"
server_ip_fail_msg: "Failed, Declare server_ip variable in nfs_client_params of storage_config, please refer comments in storage_config.yml"
client_share_path_success_msg: "Successfully verified client_share_path variable declaration"
client_share_path_fail_msg: "Failed, Declare client_share_path variable in nfs_client_params of storage_config, please refer comments in storage_config.yml"
server_share_path_len_success_msg: "server_share_path validated successfully"
client_mount_options_success_msg: "client_mount_options declaration validated successfully"
client_mount_options_fail_msg: "Failed, please declare client_mount_options variable in nfs_client_params"
server_ip_msg: "As server_ip is not available NFS bolt-on role will not work"
nfs_client_declaration_msg: "Make sure to declare values in server_ip and server_share_path in all the lists on nfs_client_params"

# Usage: fetch_beegfs_inputs.yml, fetch_nfs_client_params.yml
ping_msg: "100% packet loss"
storage_config_vars: "{{ role_path }}/../../../input/storage_config.yml"
