#  Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Initialize login_node_required status
  ansible.builtin.set_fact:
    login_node_required: false

- name: Set login_node_required to true
  ansible.builtin.set_fact:
    login_node_required: true
  when:
    - groups['login'] is defined
    - "groups['login'] | length | int == 1"

- name: Fail when more than 1 login node provided
  ansible.builtin.fail:
    msg: "{{ multiple_login_node_fail_msg }}"
  when:
    - groups['login'] is defined
    - "groups['login'] | length | int > 1"

- name: Warning when login node not provided
  ansible.builtin.pause:
    seconds: "{{ warning_wait_time }}"
    prompt: "{{ login_node_warning_msg }}"
  when: groups['login'] is not defined
