# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

#***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.                  
# SIMPLY APPEND THE REQUIRD VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
#***********************************************************************

# This variable accepts the amd gpu version for the RHEL specific OS version
# Verify if the version provided is present in the repo for the OS version on your node
# Verify the url for the compatible version: https://repo.radeon.com/amdgpu/
# If 'latest' is provided in the variable and the compute os version is rhel 8.5
# Then the url transforms to https://repo.radeon.com/amdgpu/latest/rhel/8.5/main/x86_64/ 
amd_gpu_version: "22.20.3"

# This variable accepts the amd rocm version required
# Make sure the subscription is enabled for rocm installation because rocm packages are present
# in code ready builder repo for RHEL
# If 'latest' is provided in the variable, the url transforms to
# https://repo.radeon.com/rocm/centos8/latest/main/
# Only single instance is supported by Omnia
amd_rocm_version: "latest/main"

# This variable is used to download cuda toolkit file.
# By default latest cuda is installed unless cuda_toolkit_path is specified.
# Default: latest (11.8.0)
cuda_toolkit_version: "latest"

# This variable is used to give offline rpm file for cuda toolkit.
# If cuda_toolkit_version is not latest, giving cuda_toolkit_path is mandatory.
cuda_toolkit_path: ""

# This variable is used to set stream for nvidia drivers
# Default: latest-dkms
cuda_stream: "latest-dkms"
