#  Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

#***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.                  
# SIMPLY APPEND THE REQUIRD VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
#***********************************************************************

# This variable accepts the user name for which passwordless ssh needs to be setup
# Eg. user_name: "user1,user2,user3"
user_name: ""

# Variable indicating whether FreeIPA or LDAP is setup
# It can be "freeipa" or "ldap"
# Default value: freeipa
authentication_type: "freeipa"

# This variable accepts the user home directory path for freeIPA configuration
# If nfs mount is created for user home, make sure you provide the
# users mount home directory path
# Default value: /home/omnia-share
freeipa_user_home_dir: "/home/omnia-share"

# Distinguished name i.e dn in ldap is used to identify an entity in a ldap
# This variable includes the organizational unit (ou) which is used to identifies user in the ldap
# Eg. if dn: uid=user1,ou=people,dc=omnia,dc=test
# Only provide ou details i.e ou=people, as domain name and userid is accepted already
# Default value: people
ldap_organizational_unit: "people"
