# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: main.yml
package_update_config_file: "{{ role_path }}/../../package_update_config.yml"
xcat_root_env: "/opt/xcat"
xcat_path_env: "/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools"
xcat_manpath_env: "/opt/xcat/share/man:$MANPATH"
perl_badlang_env: 0

# Usage: reboot_nodes.yml
reboot_fail_msg: "Failed. Nodes should be rebooted manually for snmpwalk and/or mapping discovery mechanisms."

# Usage: validate_input.yml
pkg_dir_success_msg: "Package directory successfully validated"
pkg_dir_fail_msg: "Failed. Check whether valid os details are provided in package_update_config.yml."
pkg_list_success_msg: "Package list successfully validated"
pkg_list_fail_msg: "Failed. Check whether valid package list is provided in package_update_config.yml."
pkg_type_success_msg: "Package type successfully validated"
pkg_type_fail_msg: "Failed. Check whether valid package type is provided in package_update_config.yml."
os_version_success_msg: "OS version successfully validated"
os_version_fail_msg: "Failed. Check whether valid os_version is provided in package_update_config.yml."
list_format_success_msg: "Package list format validated."
list_format_fail_msg: "Failed, Package list format incorrect, follow 'custom_software/<package>' format in package list."
pkg_list_missing_msg: "Failed. Package list not present in the given path {{ package_list }}.
Please provide correct path in package_update_config.yml."

# Usage: update.yml
updatenode_fail_msg: "Updatenode execution failed."
osimage_search_key: install-compute
update_node_status_msg: "Update package task completed. If updatestatus mentioned as failed for the node in below task output,
please search with key 'updatenode {{ nodelist }}'' in /var/log/xcat/commands.log and check node provision or boot status to debug the failure"
