# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Setup nfs server on manager node when enable_omnia_nfs is set to true
  when: hostvars['127.0.0.1']['enable_omnia_nfs']
  block:
    - name: Install nfs-utils
      ansible.builtin.package:
        name: nfs-utils
        state: present
      tags: nfs_server

    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present
      tags: firewalld

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      tags: firewalld

    - name: Start and enable rpcbind and nfs-server service
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - rpcbind
        - nfs-server
      tags: nfs_server

    - name: Creating NFS share directory
      ansible.builtin.file:
        path: "{{ hostvars['127.0.0.1']['omnia_usrhome_share'] }}"
        state: directory
        mode: "{{ nfs_share_dir_mode }}"
      tags: nfs_server

    - name: Adding NFS share entries in /etc/exports for compute node
      ansible.builtin.lineinfile:
        path: "{{ exports_file_path }}"
        line: "{{ hostvars['127.0.0.1']['omnia_usrhome_share'] }} {{ item }}(rw,sync,no_root_squash)"
      with_items:
        - "{{ groups['compute'] }}"
      tags: nfs_server

    - name: Adding NFS share entries in /etc/exports for login node
      ansible.builtin.lineinfile:
        path: "{{ exports_file_path }}"
        line: "{{ hostvars['127.0.0.1']['omnia_usrhome_share'] }} {{ item }}(rw,sync,no_root_squash)"
      with_items:
        - "{{ groups['login'] }}"
      when: hostvars['127.0.0.1']['login_node_required']
      tags: nfs_server

    - name: Exporting the shared directories
      ansible.builtin.command: exportfs -r
      changed_when: true
      tags: nfs_server

    - name: Configuring firewall
      ansible.builtin.command: "firewall-cmd --permanent --add-service={{ item }}"
      changed_when: true
      with_items:
        - "{{ nfs_services }}"
      tags: nfs_server

    - name: Reload firewalld
      ansible.builtin.command: firewall-cmd --reload
      changed_when: true
      tags: nfs_server

    - name: Stop and disable firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no
      tags: firewalld