---
k8s_versions:
  - 1.20.15
  - 1.21.14
  - 1.22.15
  - 1.23.17

upgrade_k8s_packages:
  - "kubelet-{{ item }}-0"
  - "kubectl-{{ item }}-0"
  - "kubeadm-{{ item }}-0"

versionlock_k8s_packages:
  - "kubelet*"
  - "kubectl*"
  - "kubeadm*" 
