---
- name: " Upgrade K8s Manager Node "
  hosts: manager
  become: true
  gather_facts: true
  serial: 1
  roles:
    - role: upgrade-manager
      tags: manager

- name: "Upgrade k8s Compute Nodes "
  hosts: compute
  become: true
  gather_facts: true
  serial: 2

  roles:
    - role: upgrade-compute
      tags: compute
